apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagination-backend-k8s-deployment  # Updated deployment name
spec:
  selector:
    matchLabels:
      app: pagination_backend-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: pagination_backend-k8s
    spec:
      containers:
        - name: pagination-backend-k8s  # Updated container name
          image: 510599/pagination_backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: pagination-backend-k8s-svc  # Updated service name
spec:
  selector:
    app: pagination_backend-k8s
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
